[package]
name = "qd"
version = "0.1.1"
edition = "2021"
authors = ["sarah <>"]
description = "Extended precision floating point arithmetic"
readme = "README.md"
repository = "https://github.com/sarah-ek/qd/"
license = "MIT"
keywords = ["math", "floating-point", "precision"]

[dependencies]
pulp = "0.13"
faer-core = { version = "0.9.1", optional = true }

[features]
default = ["faer"]
faer = ["faer-core"]

[dev-dependencies]
rug = "1.19.2"
