[package]
name = "qd"
version = "0.2.0"
edition = "2021"
authors = ["sarah <>"]
description = "Extended precision floating point arithmetic"
readme = "README.md"
repository = "https://github.com/sarah-ek/qd/"
license = "MIT"
keywords = ["math", "floating-point", "precision"]

[dependencies]
pulp = "0.14"
bytemuck = "1.0"
faer-entity = { version = "0.12.0", optional = true }

[features]
default = ["faer"]
faer = ["faer-entity"]

[dev-dependencies]
rug = "1.19.2"
