[package]
name = "qd"
version = "0.4.0"
edition = "2021"
authors = ["sarah <>"]
description = "Extended precision floating point arithmetic"
readme = "README.md"
repository = "https://github.com/sarah-ek/qd/"
license = "MIT"
keywords = ["math", "floating-point", "precision"]

[dependencies]
pulp = "0.18.8"
bytemuck = "1.0"
faer-entity = { version = "0.17.0", optional = true, default-features = false }

[features]
default = ["faer", "std"]
std = ["pulp/std", "faer-entity/std"]
faer = ["faer-entity"]

[dev-dependencies]
criterion = "0.5.1"
rug = "1.19.2"

[[bench]]
name = "bench"
harness = false
