[package]
name = "qd"
version = "0.6.0"
edition = "2021"
authors = ["sarah <>"]
description = "Extended precision floating point arithmetic"
readme = "README.md"
repository = "https://github.com/sarah-ek/qd/"
license = "MIT"
keywords = ["math", "floating-point", "precision"]

[dependencies]
pulp = "0.18.21"
bytemuck = "1.0"
faer-entity = { version = "0.19.0", optional = true, default-features = false }
libm = "0.2.8"
coe-rs = "0.1.2"
num-traits = "0.2.19"

[features]
default = ["faer", "std"]
std = ["pulp/std", "faer-entity/std"]
faer = ["faer-entity"]

[dev-dependencies]
aligned-vec = "0.5.0"
equator = "0.1.10"
rand = "0.8.5"
rug = "1.19.2"
pulp = { version = "0.18.8", features = ["nightly"] }
divan = "0.1.14"

[[bench]]
name = "bench"
harness = false
